name: SaltyEconomy
version: ${project.version}
main: de.frozenius.saltyeconomy.Main
api-version: 1.15
authors: [Frozenius]
description: Salty Own Economy Plugin by Frozenius

commands:
  bp:
    description: Gibt dir einen Rucksack
  money:
    description: Zeigt deinen aktuellen Kontostand
  pay:
    description: Überweist Geld
  setmoney:
    description: Setzt deinen Kontostand
  removemoney:
    description: Senkt deinen Kontostand
  addmoney:
    description: Fügt deinem Konto Geld hinzu